import type { Lang } from './types';

/* All UI copy, ES (default) + EN. Original text written for Jon OS. */

type Dict = Record<string, any>;

const es: Dict = {
  boot: {
    title: 'JON OS',
    msgs: ['Cargando kernel…', 'Montando /dev/ideas…', 'Calibrando neones…', 'Iniciando Jon OS…'],
  },
  lock: {
    unlock: 'Desbloquear',
    recruiter: 'Soy reclutador',
    hint: 'Mejor en pantalla completa · pulsa F11',
    lang: 'Idioma',
  },
  recruiter: {
    hey: 'Hola, soy Jon Peciña',
    role: 'AI Engineer',
    body: 'Construyo aplicaciones completas aceleradas por IA: juegos 3D, plataformas educativas, trading algorítmico y herramientas. Todo el código, del frontend al despliegue, sale de mis manos.',
    viewCv: 'Ver CV',
    projects: 'Proyectos destacados',
    downloadCv: 'Descargar CV',
    contact: 'Contacto',
    copyEmail: 'Copiar email',
    copied: 'Email copiado al portapapeles',
    enter: 'Entrar al escritorio',
  },
  desktop: {
    hint: 'Haz clic en un icono para abrir una app. El botón de inicio abre el resto.',
    hintClose: 'Entendido',
  },
  start: {
    search: 'Buscar apps…',
    noResults: 'Sin resultados',
    recruiter: 'Modo reclutador',
    lock: 'Bloquear',
    about: 'Acerca de',
  },
  apps: {
    about: 'Sobre mí',
    projects: 'Proyectos',
    project: 'Proyecto',
    resume: 'Currículum',
    contact: 'Contacto',
    terminal: 'Terminal',
    achievements: 'Logros',
    settings: 'Ajustes',
    help: 'Ayuda',
  },
  about: {
    role: 'AI Engineer',
    location: 'Logroño, España · UTC+1 · Remoto',
    available: 'Disponible',
    bio: 'Ingeniero Industrial (UNAV) convertido en AI Engineer. Construyo aplicaciones completas — frontend, backend, testing y DevOps — aceleradas con herramientas de IA como Claude, Codex y OpenCode. Especializado en agentes de IA, RAG y LLMs, sobre una base full-stack sólida en React, Node.js y PostgreSQL.',
    specs: [
      {
        title: 'Ingeniería de IA',
        desc: 'Agentes de IA, pipelines RAG y apps con LLMs llevados a producción, no demos.',
        chips: ['Python', 'LangChain', 'RAG', 'LLMs', 'AI Agents'],
      },
      {
        title: 'Full-Stack Web',
        desc: 'Aplicaciones completas del modelo de datos al último píxel.',
        chips: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'],
      },
      {
        title: '3D y Juegos',
        desc: 'Juegos 3D para navegador con física, audio y mando.',
        chips: ['Three.js', 'WebGL', 'Web Audio', 'Gamepad API'],
      },
    ],
    viewProjects: 'Ver proyectos',
    videoTitle: 'Fuera del teclado',
    videoCap1: 'Escalada en roca — la misma obsesión por la precisión, en vertical.',
    videoCap2: 'BTT de montaña — velocidad, técnica y polvo.',
    resume: 'Currículum',
    contact: 'Contacto',
    elsewhere: 'ELSEWHERE',
    copyEmail: 'Copiar',
    copied: 'Email copiado',
  },
  projects: {
    title: 'Proyectos de Jon',
    search: 'Buscar por nombre o tecnología…',
    featured: 'DESTACADOS',
    more: 'MÁS PROYECTOS',
    count: (t: number, s: number) => `${t} proyectos · ${s} en producción`,
    starred: 'Añadido a favoritos',
    unstarred: 'Quitado de favoritos',
    noResults: 'Ningún proyecto coincide con la búsqueda.',
    openSite: 'Abrir sitio',
    viewCode: 'Ver código',
    statusShipped: 'En producción',
    statusCode: 'Código',
    statusDev: 'En desarrollo',
    role: 'Rol',
    date: 'Fecha',
    problem: 'PROBLEMA',
    did: 'QUÉ HICE',
    stack: 'STACK',
    outcome: 'RESULTADO',
    next: 'Siguiente proyecto',
    prev: 'Anterior',
    newTab: 'Nueva pestaña',
  },
  resume: {
    tabs: { exp: 'Experiencia', skills: 'Habilidades', feat: 'Destacados', edu: 'Educación', lang: 'Idiomas' },
    download: 'Descargar CV',
    printHint: 'Se abrirá una versión limpia para imprimir o guardar como PDF.',
    avail: 'Remoto · Disponible desde noviembre de 2026 · UTC+1 · Contrato o freelance, con equipos en Europa o LATAM.',
    profile: 'AI Engineer con base sólida full-stack: Ingeniería Industrial (UNAV) y Máster Full Stack Developer (UNIR). Construyo aplicaciones completas — frontend, backend, testing y DevOps — aceleradas por IA, del concepto al despliegue en días, con verificación rigurosa y sin atajos en calidad.',
    exp: [
      {
        title: 'AI Engineer — Independiente',
        where: 'Logroño / Remoto',
        when: '2024 — Actualidad',
        desc: 'Diseño y entrega de aplicaciones completas aceleradas por IA: más de 10 productos publicados — juegos 3D, plataformas educativas, trading algorítmico y herramientas — del frontend al despliegue, sin backend donde es posible.',
      },
      {
        title: 'Carrera en Finanzas',
        where: 'España · Países Bajos · Perú',
        when: '2004 — 2026',
        desc: '22 años en finanzas — Director de Servicios Corporativos (Surexport Perú, Lima), Financial Accountant (Avolta, Barcelona/Eindhoven), Finance Director y Controller (UNIBAÑO SL, Logroño). Base analítica que hoy aplico a la ingeniería de IA.',
      },
    ],
    skillGroups: [
      { name: 'Ingeniería de IA', skills: [['Python', 90, 'Avanzado'], ['AI Agents', 90, 'Avanzado'], ['LLMs', 90, 'Avanzado'], ['RAG', 85, 'Avanzado'], ['LangChain', 85, 'Avanzado'], ['Prompt Engineering', 90, 'Avanzado'], ['Desarrollo asistido por IA', 90, 'Avanzado']] },
      { name: 'Full-Stack', skills: [['React', 70, 'Intermedio'], ['TypeScript', 70, 'Intermedio'], ['JavaScript', 85, 'Avanzado'], ['Node.js', 70, 'Intermedio'], ['Express', 70, 'Intermedio'], ['REST APIs', 80, 'Avanzado'], ['WebSocket', 70, 'Intermedio']] },
      { name: 'Bases de datos', skills: [['PostgreSQL', 70, 'Intermedio'], ['MySQL', 80, 'Avanzado'], ['Diseño de esquemas', 80, 'Avanzado'], ['Optimización de consultas', 75, 'Avanzado']] },
      { name: 'Cuantitativo', skills: [['Estrategias algorítmicas', 75, 'Avanzado'], ['Backtesting', 75, 'Avanzado'], ['Indicadores técnicos', 80, 'Avanzado'], ['Optimización de parámetros', 70, 'Intermedio']] },
      { name: '3D e interactivo', skills: [['Three.js', 80, 'Avanzado'], ['WebGL', 70, 'Intermedio'], ['HTML5 Canvas', 80, 'Avanzado'], ['Web Audio', 85, 'Avanzado'], ['Gamepad API', 80, 'Avanzado']] },
      { name: 'DevOps y calidad', skills: [['Docker', 65, 'Intermedio'], ['Railway', 70, 'Intermedio'], ['Git & GitHub', 85, 'Avanzado'], ['Verificación headless/en navegador', 85, 'Avanzado'], ['Testing CI-friendly', 80, 'Avanzado']] },
    ],
    featured: [
      { slug: 'futbol3d', name: 'Fútbol 3D', desc: 'Simulador de partidos 11 contra 11 en 3D a tiempo real.', stack: 'Three.js · JavaScript · 3D en tiempo real · WebGL' },
      { slug: 'tsla', name: 'TSLA Trading Agent', desc: 'Sistema de trading algorítmico con backtesting y optimizador de parámetros.', stack: 'Python · REST · WebSocket · trading algorítmico · análisis cuantitativo' },
      { slug: 'erp3', name: 'ERP Enterprise', desc: 'Sistema empresarial completo con 20 módulos y API REST segura.', stack: 'React · Vite · REST API · token auth · i18n' },
      { slug: 'neon-escape', name: 'NEON ESCAPE', desc: 'Juego arcade de conducción 3D en un mundo synthwave, sin backend.', stack: 'Vite · React · Three.js · JavaScript · Web Audio · Gamepad API' },
    ],
    howIWork: 'Responsabilidad end-to-end (front, back, testing, DevOps — sin traspasos); acelerado por IA, con verificación primero — revisado y probado antes de publicar.',
    edu: [
      { title: 'Máster en Full Stack Developer', place: 'UNIR — Universidad Internacional de La Rioja' },
      { title: 'Ingeniería Industrial', place: 'Universidad de Navarra (UNAV)' },
    ],
    langs: [['Español', 'Nativo'], ['Inglés', 'Profesional']],
  },
  contact: {
    title: 'Contacto',
    sub: 'Remoto · Disponible desde noviembre de 2026 · UTC+1. Contrato o freelance, con equipos en Europa o LATAM.',
    copyEmail: 'Copiar email',
    copied: 'Email copiado al portapapeles',
    subject: '¿De qué se trata?',
    subjects: [
      { id: 'general', t: 'Consulta general', d: 'Preguntas, feedback o saludos' },
      { id: 'hiring', t: 'Contratación', d: 'Ofertas de empleo o freelance' },
      { id: 'meeting', t: 'Reunión', d: 'Agendar una llamada' },
      { id: 'bug', t: 'Error', d: 'Algo no funciona…' },
    ],
    name: 'Nombre',
    email: 'Email',
    message: 'Mensaje',
    namePh: 'Tu nombre',
    emailPh: 'tu@email.com',
    messagePh: 'Cuéntame en qué puedo ayudarte…',
    send: 'Enviar mensaje',
    opening: 'Abriendo tu cliente de correo…',
    note: 'Sin backend: esto abre tu app de correo con el mensaje ya redactado. Nada se envía solo.',
    errors: { name: 'Escribe tu nombre', email: 'Email no válido', message: 'Escribe un mensaje' },
  },
  terminal: {
    welcome: ['Jon OS terminal · escribe "help" para ver los comandos.', ''],
    helpTitle: 'Comandos disponibles:',
    unknown: (c: string) => `comando no encontrado: ${c} — escribe "help"`,
    prompt: 'jon@jon-os',
  },
  achievements: {
    title: 'Logros',
    level: 'NIVEL',
    xpBar: (x: number, y: number) => `${x} / ${y} XP`,
    unlocked: (n: number, t: number) => `${n} de ${t} desbloqueados`,
    locked: 'Bloqueado',
    levels: ['Novato', 'Explorador', 'Usuario avanzado', 'Hacker', 'Leyenda'],
  },
  settings: {
    title: 'Ajustes',
    accent: 'Acento',
    accentDesc: 'Color principal del sistema',
    wallpaper: 'Fondo',
    wallpaperDesc: 'Fondo de escritorio animado',
    wallpapers: { nebula: 'Nebulosa', starfield: 'Campo de estrellas', matrix: 'Lluvia matrix', dark: 'Oscuro puro' },
    uiSize: 'Tamaño de interfaz',
    uiSizeDesc: 'Escala del texto del sistema',
    sizes: { normal: 'Normal', large: 'Grande' },
    theme: 'Tema',
    themeDesc: 'Apariencia de ventanas y menús',
    themes: { dark: 'Oscuro', light: 'Claro' },
    accents: { aqua: 'Aqua', cyan: 'Cian', blue: 'Azul', violet: 'Violeta', amber: 'Ámbar' },
  },
  help: {
    title: 'Ayuda',
    intro: 'Jon OS es un portfolio interactivo con forma de sistema operativo. Todo funciona en tu navegador: sin cuentas, sin backend y sin rastreo.',
    rows: [
      ['Abrir apps', 'Haz clic en un icono del escritorio o busca en el menú de inicio.'],
      ['Mover ventanas', 'Arrastra desde la barra de título.'],
      ['Minimizar / maximizar', 'Botones − y □ en la barra de título, o clic en el icono de la barra de tareas.'],
      ['Cerrar', 'Botón × en la barra de título, o comando "exit" en la terminal.'],
      ['Cambiar idioma', 'Botón ES/EN en la pantalla de bloqueo o en la barra de tareas.'],
      ['Código Konami', '↑ ↑ ↓ ↓ ← → ← → B A en cualquier lugar…'],
    ],
    aboutSite: 'Acerca de este sitio',
    aboutSiteBody: 'Jon OS v1.0 — construido con React, sin backend, sin tracking. Código 100% original.',
  },
  toasts: {
    achievement: 'Logro desbloqueado',
  },
  tray: {
    lang: 'Idioma',
    settings: 'Ajustes',
  },
};

const en: Dict = {
  boot: {
    title: 'JON OS',
    msgs: ['Loading kernel…', 'Mounting /dev/ideas…', 'Calibrating neon…', 'Starting Jon OS…'],
  },
  lock: {
    unlock: 'Unlock',
    recruiter: "I'm a recruiter",
    hint: 'Best in fullscreen · press F11',
    lang: 'Language',
  },
  recruiter: {
    hey: "Hi, I'm Jon Peciña",
    role: 'AI Engineer',
    body: 'I build complete AI-accelerated applications: 3D games, learning platforms, algorithmic trading and tools. All the code — from frontend to deployment — is written by me.',
    viewCv: 'View CV',
    projects: 'Featured projects',
    downloadCv: 'Download CV',
    contact: 'Contact',
    copyEmail: 'Copy email',
    copied: 'Email copied to clipboard',
    enter: 'Enter desktop',
  },
  desktop: {
    hint: 'Click an icon to open an app. The start button opens the rest.',
    hintClose: 'Got it',
  },
  start: {
    search: 'Search apps…',
    noResults: 'No results',
    recruiter: 'Recruiter mode',
    lock: 'Lock',
    about: 'About',
  },
  apps: {
    about: 'About Me',
    projects: 'Projects',
    project: 'Project',
    resume: 'Resume',
    contact: 'Contact',
    terminal: 'Terminal',
    achievements: 'Achievements',
    settings: 'Settings',
    help: 'Help',
  },
  about: {
    role: 'AI Engineer',
    location: 'Logroño, Spain · UTC+1 · Remote',
    available: 'Available',
    bio: 'Industrial Engineer (UNAV) turned AI Engineer. I build complete applications — frontend, backend, testing and DevOps — accelerated with AI tools like Claude, Codex and OpenCode. Specialized in AI agents, RAG and LLMs, on a solid full-stack foundation in React, Node.js and PostgreSQL.',
    specs: [
      {
        title: 'AI Engineering',
        desc: 'AI agents, RAG pipelines and LLM apps shipped to production, not demos.',
        chips: ['Python', 'LangChain', 'RAG', 'LLMs', 'AI Agents'],
      },
      {
        title: 'Full-Stack Web',
        desc: 'Complete applications from the data model to the last pixel.',
        chips: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'],
      },
      {
        title: '3D & Games',
        desc: 'Browser 3D games with physics, audio and gamepad support.',
        chips: ['Three.js', 'WebGL', 'Web Audio', 'Gamepad API'],
      },
    ],
    viewProjects: 'View projects',
    videoTitle: 'Off the keyboard',
    videoCap1: 'Rock climbing — the same obsession with precision, gone vertical.',
    videoCap2: 'Mountain biking — speed, technique and dust.',
    resume: 'Resume',
    contact: 'Contact',
    elsewhere: 'ELSEWHERE',
    copyEmail: 'Copy',
    copied: 'Email copied',
  },
  projects: {
    title: "Jon's projects",
    search: 'Search by name or technology…',
    featured: 'FEATURED',
    more: 'MORE PROJECTS',
    count: (t: number, s: number) => `${t} projects · ${s} shipped`,
    starred: 'Added to favorites',
    unstarred: 'Removed from favorites',
    noResults: 'No project matches your search.',
    openSite: 'Open site',
    viewCode: 'View code',
    statusShipped: 'Shipped',
    statusCode: 'Code',
    statusDev: 'In development',
    role: 'Role',
    date: 'Date',
    problem: 'PROBLEM',
    did: 'WHAT I DID',
    stack: 'STACK',
    outcome: 'OUTCOME',
    next: 'Next project',
    prev: 'Previous',
    newTab: 'New tab',
  },
  resume: {
    tabs: { exp: 'Experience', skills: 'Skills', feat: 'Featured', edu: 'Education', lang: 'Languages' },
    download: 'Download CV',
    printHint: 'A clean print-optimized version will open for printing or saving as PDF.',
    avail: 'Remote · Available from November 2026 · UTC+1 · Contract or freelance, with teams in Europe or LATAM.',
    profile: 'AI Engineer rebuilt on top of a strong full-stack career: Industrial Engineering degree (UNAV) plus a Master in Full Stack Development (UNIR). I build complete applications — front-end, back-end, testing and DevOps — amplified by AI tooling, from idea to deployed reality in days, rigorously reviewed and verified, without shortcuts on quality.',
    exp: [
      {
        title: 'AI Engineer — Independent',
        where: 'Logroño / Remote',
        when: '2024 — Present',
        desc: 'Design and delivery of complete AI-accelerated applications: 10+ shipped products — 3D games, learning platforms, algorithmic trading and tools — from frontend to deployment, backend-free wherever possible.',
      },
      {
        title: 'Finance career',
        where: 'Spain · Netherlands · Peru',
        when: '2004 — 2026',
        desc: '22 years in finance — Corporate Services Director (Surexport Perú, Lima), Financial Accountant (Avolta, Barcelona/Eindhoven), Finance Director & Controller (UNIBAÑO SL, Logroño). An analytical foundation I now apply to AI engineering.',
      },
    ],
    skillGroups: [
      { name: 'AI Engineering', skills: [['Python', 90, 'Advanced'], ['AI Agents', 90, 'Advanced'], ['LLMs', 90, 'Advanced'], ['RAG', 85, 'Advanced'], ['LangChain', 85, 'Advanced'], ['Prompt Engineering', 90, 'Advanced'], ['AI-assisted development', 90, 'Advanced']] },
      { name: 'Full-Stack', skills: [['React', 70, 'Intermediate'], ['TypeScript', 70, 'Intermediate'], ['JavaScript', 85, 'Advanced'], ['Node.js', 70, 'Intermediate'], ['Express', 70, 'Intermediate'], ['REST APIs', 80, 'Advanced'], ['WebSocket', 70, 'Intermediate']] },
      { name: 'Databases', skills: [['PostgreSQL', 70, 'Intermediate'], ['MySQL', 80, 'Advanced'], ['Schema design', 80, 'Advanced'], ['Query optimization', 75, 'Advanced']] },
      { name: 'Quantitative', skills: [['Algorithmic strategies', 75, 'Advanced'], ['Backtesting', 75, 'Advanced'], ['Technical indicators', 80, 'Advanced'], ['Parameter optimization', 70, 'Intermediate']] },
      { name: 'Interactive & 3D', skills: [['Three.js', 80, 'Advanced'], ['WebGL', 70, 'Intermediate'], ['HTML5 Canvas', 80, 'Advanced'], ['Web Audio', 85, 'Advanced'], ['Gamepad API', 80, 'Advanced']] },
      { name: 'DevOps & Quality', skills: [['Docker', 65, 'Intermediate'], ['Railway', 70, 'Intermediate'], ['Git & GitHub', 85, 'Advanced'], ['Headless/browser verification', 85, 'Advanced'], ['CI-friendly testing', 80, 'Advanced']] },
    ],
    featured: [
      { slug: 'futbol3d', name: 'Fútbol 3D', desc: 'Real-time 11-vs-11 3D football simulator.', stack: 'Three.js · JavaScript · real-time 3D · WebGL' },
      { slug: 'tsla', name: 'TSLA Trading Agent', desc: 'Algorithmic trading system with backtesting and a parameter optimizer.', stack: 'Python · REST · WebSocket · algorithmic trading · quantitative analytics' },
      { slug: 'erp3', name: 'ERP Enterprise', desc: 'Complete business system with 20 modules and a secure REST API.', stack: 'React · Vite · REST API · token auth · i18n' },
      { slug: 'neon-escape', name: 'NEON ESCAPE', desc: 'No-backend 3D arcade driving game in a synthwave world.', stack: 'Vite · React · Three.js · JavaScript · Web Audio · Gamepad API' },
    ],
    howIWork: 'End-to-end ownership (front, back, testing, DevOps — no handoffs); AI-accelerated, verification-first — reviewed and tested before shipping.',
    edu: [
      { title: 'Master in Full Stack Development', place: 'UNIR — Universidad Internacional de La Rioja' },
      { title: 'Industrial Engineering', place: 'Universidad de Navarra (UNAV)' },
    ],
    langs: [['Spanish', 'Native'], ['English', 'Professional']],
  },
  contact: {
    title: 'Contact',
    sub: 'Remote · Available from November 2026 · UTC+1. Contract or freelance, with teams in Europe or LATAM.',
    copyEmail: 'Copy email',
    copied: 'Email copied to clipboard',
    subject: "What's this about?",
    subjects: [
      { id: 'general', t: 'General inquiry', d: 'Questions, feedback, or just saying hi' },
      { id: 'hiring', t: 'Hiring', d: 'Job opportunities or freelance' },
      { id: 'meeting', t: 'Meeting', d: 'Set up a call' },
      { id: 'bug', t: 'Bug report', d: 'Something is not working…' },
    ],
    name: 'Name',
    email: 'Email',
    message: 'Message',
    namePh: 'Your name',
    emailPh: 'you@email.com',
    messagePh: 'Tell me how I can help…',
    send: 'Send message',
    opening: 'Opening your email client…',
    note: 'No backend: this opens your mail app with the message pre-written. Nothing is sent automatically.',
    errors: { name: 'Please write your name', email: 'Invalid email', message: 'Please write a message' },
  },
  terminal: {
    welcome: ['Jon OS terminal · type "help" to list commands.', ''],
    helpTitle: 'Available commands:',
    unknown: (c: string) => `command not found: ${c} — type "help"`,
    prompt: 'jon@jon-os',
  },
  achievements: {
    title: 'Achievements',
    level: 'LEVEL',
    xpBar: (x: number, y: number) => `${x} / ${y} XP`,
    unlocked: (n: number, t: number) => `${n} of ${t} unlocked`,
    locked: 'Locked',
    levels: ['Novice', 'Explorer', 'Power user', 'Hacker', 'Legend'],
  },
  settings: {
    title: 'Settings',
    accent: 'Accent',
    accentDesc: 'Primary system color',
    wallpaper: 'Wallpaper',
    wallpaperDesc: 'Animated desktop background',
    wallpapers: { nebula: 'Nebula', starfield: 'Starfield', matrix: 'Matrix rain', dark: 'Pure dark' },
    uiSize: 'Interface size',
    uiSizeDesc: 'System text scale',
    sizes: { normal: 'Normal', large: 'Large' },
    theme: 'Theme',
    themeDesc: 'Windows and menus appearance',
    themes: { dark: 'Dark', light: 'Light' },
    accents: { aqua: 'Aqua', cyan: 'Cyan', blue: 'Blue', violet: 'Violet', amber: 'Amber' },
  },
  help: {
    title: 'Help',
    intro: 'Jon OS is an interactive portfolio shaped like an operating system. Everything runs in your browser: no accounts, no backend, no tracking.',
    rows: [
      ['Open apps', 'Click a desktop icon or search in the start menu.'],
      ['Move windows', 'Drag from the title bar.'],
      ['Minimize / maximize', 'The − and □ buttons in the title bar, or click the taskbar icon.'],
      ['Close', 'The × button in the title bar, or the "exit" command in the terminal.'],
      ['Switch language', 'The ES/EN button on the lock screen or in the taskbar.'],
      ['Konami code', '↑ ↑ ↓ ↓ ← → ← → B A anywhere…'],
    ],
    aboutSite: 'About this site',
    aboutSiteBody: 'Jon OS v1.0 — built with React, no backend, no tracking. 100% original code.',
  },
  toasts: {
    achievement: 'Achievement unlocked',
  },
  tray: {
    lang: 'Language',
    settings: 'Settings',
  },
};

export const STR: Record<Lang, Dict> = { es, en };
